// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AdSense: typeof import('./components/publicity/AdSense.vue')['default']
    Button: typeof import('./components/input/Button.vue')['default']
    Chat: typeof import('./components/parts/Chat.vue')['default']
    Checkbox: typeof import('./components/input/Checkbox.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    DiscordAuth: typeof import('./components/auth/DiscordAuth.vue')['default']
    Entry: typeof import('./components/input/Entry.vue')['default']
    Footer: typeof import('./components/parts/Footer.vue')['default']
    FooterBis: typeof import('./components/all-components/FooterBis.vue')['default']
    GoogleAuth: typeof import('./components/auth/GoogleAuth.vue')['default']
    InfoBar: typeof import('./components/parts/NavBar/InfoBar.vue')['default']
    InstaAuth: typeof import('./components/auth/InstaAuth.vue')['default']
    Loading: typeof import('./components/style/Loading.vue')['default']
    LoginBar: typeof import('./components/parts/NavBar/LoginBar.vue')['default']
    NumAuth: typeof import('./components/auth/NumAuth.vue')['default']
    PlanningInit: typeof import('./components/pages/login/PlanningInit.vue')['default']
    PreferenceInit: typeof import('./components/pages/login/PreferenceInit.vue')['default']
    SchoolInit: typeof import('./components/pages/login/SchoolInit.vue')['default']
    SearchBox: typeof import('./components/all-components/SearchBox.vue')['default']
    Select: typeof import('./components/input/Select.vue')['default']
    SideBar: typeof import('./components/parts/NavBar/SideBar.vue')['default']
    SnapchatAuth: typeof import('./components/auth/SnapchatAuth.vue')['default']
    TopBar: typeof import('./components/parts/NavBar/TopBar.vue')['default']
    UICheckbox: typeof import('./components/all-components/UICheckbox.vue')['default']
  }
}

export { }
