// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AdSense: typeof import('./components/publicity/AdSense.vue')['default']
    Checkbox: typeof import('./components/input/Checkbox.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Entry: typeof import('./components/input/Entry.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GoogleAuth: typeof import('./components/auth/GoogleAuth.vue')['default']
    Loading: typeof import('./components/style/Loading.vue')['default']
    LoginBar: typeof import('./components/parts/LoginBar.vue')['default']
    README: typeof import('./components/README.md')['default']
    SearchBox: typeof import('./components/all-components/SearchBox.vue')['default']
    Select: typeof import('./components/input/Select.vue')['default']
    TopBar: typeof import('./components/parts/TopBar.vue')['default']
    UICheckbox: typeof import('./components/all-components/UICheckbox.vue')['default']
  }
}

export { }
