name: Deploy to Live Channel

on:
  release:
    types: [published]

env:
  PROJECT_NAME: tutorat-fde

jobs:
  deploy_prod:
    name: Deploy Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build App
        run: pnpm build || echo $?
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: '${{ env.PROJECT_NAME }}'
          channelId: live
